-- The Knowledge Oracle corpus: sources, chunks, and the vector index over them.
--
-- Generated by drizzle-kit, then hand-edited for one thing it does not emit:
-- the extension. The `embedding` column's `vector(1536)` is a type that does
-- not exist until `CREATE EXTENSION vector` has run, so without this first
-- statement the whole migration fails on the one after it. drizzle-kit models
-- the column but not the extension behind it; ADR 0005 chose Neon partly
-- because pgvector ships on every plan, and "ships" means available to enable,
-- not already enabled.
--
-- Note for whoever writes 0013: `drizzle-kit generate` ran here without the
-- no-TTY prompt that forced 0011 to be written by hand. The prompt is for
-- ambiguous renames; a pure addition does not raise it. Try the generator first.
--
-- `db:push` was removed from package.json when this landed. Push builds from
-- schema.ts and never reads these files, so it emits neither the statement
-- below nor the hand-written parts of 0011: against a database without the
-- extension it fails on `vector(1536)`, and against one with it, it succeeds
-- while leaving the journal disagreeing with the database. `db:migrate` is the
-- only path that produces a correct schema, and now the only one that looks
-- like it would.
--
-- 1536 is the dimensionality of OpenAI text-embedding-3-small (decided
-- 2026-08-21). It is baked into the column type, so changing embedding model
-- later is a migration plus a full re-ingest, not a config edit.
CREATE EXTENSION IF NOT EXISTS vector;--> statement-breakpoint
CREATE TABLE "knowledge_chunks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	"text" text NOT NULL,
	"token_estimate" integer NOT NULL,
	"embedding" vector(1536) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "knowledge_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"authors" text NOT NULL,
	"year" integer NOT NULL,
	"doi" text,
	"pmcid" text,
	"licence" text NOT NULL,
	"licence_url" text NOT NULL,
	"attribution" text NOT NULL,
	"text_digest" text NOT NULL,
	"ingested_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_sources_slug_unique" UNIQUE("slug"),
	CONSTRAINT "knowledge_sources_licence_present" CHECK (length("knowledge_sources"."licence") > 0)
);
--> statement-breakpoint
ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "knowledge_chunks_source_id_knowledge_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "knowledge_chunks_embedding_idx" ON "knowledge_chunks" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_chunks_source_ordinal_idx" ON "knowledge_chunks" USING btree ("source_id","ordinal");