// Generated by scripts/product-brief.mjs — do not edit.
// Regenerate from the code repo root with `node scripts/product-brief.mjs <docs-root>`, where
// <docs-root> is the private docs repo. Sources there: CONTEXT-BRIEF.md and
// .scratch/post-testing/planned-features.md.

/** What the app is, one product term per line, for the Feedback Interview (showable-version/58). */
export const PRODUCT_BRIEF: readonly string[] = [
  "Target Athlete: Serious amateur Ironman triathlete.",
  "Onboarding Session: the structured first meeting between Momentum and athlete, delivered as a deliberately large, buttoned MCQ inflow.",
  "First Week Plan: the Week Plan a newly-onboarded athlete receives, covering the remainder of their current week rather than the next one, so onboarding ends with training to do rather than a wait.",
  "Training Plan: Momentum's rolling view of the athlete's upcoming training, presented as a monthly calendar grid with a Momentum narrative alongside.",
  "Week Plan: Momentum's recommended session schedule for the current 7-day window, derived from Training Phase and the athlete's accumulated history.",
  "Planned Session: a session recommended by Momentum for a future day, as part of the Week Plan.",
  "Session Type: the category of a Planned Session, used for colour-coding in the Training Plan calendar.",
  "Session Move: a relocation of a session to a different day, performed by dragging the session chip in the Training Plan calendar.",
  "Athlete Session: a session authored by the athlete rather than Momentum, created via a \"+\" on a day inside an Expanded Week (opens the Session Drawer in create mode: type, optional duration, optional note).",
  "Session Drawer: the single detail surface for sessions: a panel that slides in from the right, mirroring the Navigation Drawer's behavior (overlaps the content area, dismissed by tapping outside or closing).",
  "Session Feedback Prompt: a popup surfaced when the athlete marks a session complete via a \"Mark complete\" button on a Planned Session in the Training Plan calendar.",
  "Session Reflection: the post-session ritual.",
  "Body Feedback: the physical dimension of Session Reflection.",
  "Mind Feedback: the mental and emotional dimension of Session Reflection.",
  "RPE (Rate of Perceived Exertion): the 1–10 scale Body Feedback and Mind Feedback are expressed on.",
  "Coach Overlay: the always-available surface for the one Momentum conversation, replacing the former Coach View as a navigation destination.",
  "Training Block: a named span of weeks with one purpose, between two and six of them across an athlete's horizon.",
  "Training Phase: the name of the Training Block today falls inside.",
  "Race: an event the athlete has entered or intends to: a name, a date, and a Race Distance.",
  "Target Race: the Race the athlete is currently building toward.",
  "Injury: a part of the athlete's body that has stopped some training, with no scheduled end.",
  "Illness: a systemic reduction in the athlete's capacity, affecting everything at once, with no scheduled end.",
  "Leave: time away from home with capacity fully intact: a holiday, a work trip.",
  "Unavailable: the athlete-declared \"training can't happen here\" state, at two granularities.",
  "History Upload: the athlete's past training brought in from Garmin files, in onboarding or from Settings, written straight into the record as completed history.",
  "Detected Activity: a completed activity arriving into the app, reconciled against the Week Plan.",
  "Information View: the data View: where the athlete (and, in Coached Mode, the Head Coach) oversees training and bodily information over time.",
  "Glossary: the View holding term-and-definition reference for the training language the athlete meets in the plan and in Momentum's messages (RPE, Zone 2, brick, taper, FTP).",
  "Navigation Drawer: a toggleable sidebar that opens and overlaps ~20% of the main content area.",
  "Head Coach: the human coach overseeing a Roster of athletes.",
];

/** Features that are planned, not built. The interviewer never raises these first. */
export const PLANNED_FEATURES: readonly string[] = [
  "Every session explains itself: warm-up, main set and cool-down with minutes and zones, plus what to focus on.",
  "Races in the calendar: add a target or tune-up race from any day; race days stand out.",
  "A plan with no race booked: a six-month training arc for athletes without a target race.",
  "The coach notices patterns: Momentum points out trends in your ratings, skipped sessions and device data.",
  "Finish-time prediction: an estimate of your race time if you follow the plan.",
  "Live watch sync: activities arrive from your watch without exporting files.",
  "Talking changes the plan: ask Momentum to change a session and confirm with one tap.",
  "Inviting your own coach: a human coach can invite you by email and follow your training.",
];
