import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { renderGeneratedModule } from '../../../scripts/product-brief.mjs';
import { PLANNED_FEATURES, PRODUCT_BRIEF } from './product-brief.generated';

/**
 * `showable-version/58` — the checked-in brief the Feedback Interview reads.
 *
 * The docs it is condensed from are not in this repo, so this cannot rerun the
 * script against them. What it can pin: the file is byte for byte what the
 * script renders for its own contents (so it was generated, not hand-edited),
 * it fits the prompt budget, and it carries nothing about a person.
 */

const source = readFileSync(new URL('product-brief.generated.ts', import.meta.url), 'utf8');
const everyLine = [...PRODUCT_BRIEF, ...PLANNED_FEATURES];

/**
 * Under the hardening gate, Stryker rewrites the file on disk to switch its
 * mutants in and out, so its bytes are no longer the checked-in file and the two
 * byte checks below cannot hold in its dry run. They are skipped there and only
 * there. The literals are still mutated, and the golden prompt snapshots
 * (`feedback-prompt.golden.test.ts`) carry every line, so they kill each mutant.
 */
const instrumented = /^\/\/ @ts-nocheck|stryMutAct_/.test(source);

describe.skipIf(instrumented)('product-brief.generated.ts, as bytes on disk', () => {
  it('the checked-in brief is what the script produces', () => {
    expect(PRODUCT_BRIEF.length).toBeGreaterThan(0);
    expect(PLANNED_FEATURES.length).toBeGreaterThan(0);
    expect(source).toBe(renderGeneratedModule(PRODUCT_BRIEF.join('\n'), [...PLANNED_FEATURES]));
  });

  it('says it is generated, and how to regenerate it', () => {
    expect(source.split('\n')[0]).toBe('// Generated by scripts/product-brief.mjs — do not edit.');
    expect(source).toContain('node scripts/product-brief.mjs <docs-root>');
  });
});

describe('product-brief.generated.ts', () => {
  it('fits the prompt budget', () => {
    expect(PRODUCT_BRIEF.join('\n').length).toBeLessThan(4000);
  });

  it('holds nothing about any athlete or tester', () => {
    // Contact details, the owner's name, and the four test personas
    // (`.claude/skills/use-me`) — the names most likely to leak into a doc.
    for (const line of everyLine) {
      expect(line).not.toMatch(/@|\+\d|\d(?:[\s-]?\d){7,}/);
      expect(line).not.toMatch(/madskilstrup|\bMads\b|\bSarah\b|\bThomas\b|\bMarcus\b|\bEmma\b/i);
    }
  });

  it('calls the Coach Momentum, as the interviewer prompt must', () => {
    for (const line of everyLine) expect(line).not.toMatch(/\bthe Coach\b/);
  });
});
