#!/usr/bin/env node
/**
 * Generates `CONTEXT-BRIEF.md` — the per-session digest of `OVERVIEW.md` and
 * `CONTEXT.md` that `CLAUDE.md` imports in their place.
 *
 * Why this exists (2026-09-15, `.scratch/research/ecc-workflow-comparison.md`
 * §7): `CLAUDE.md` used to `@`-import the whole glossary (~28k tokens) and the
 * whole overview (~10k) into every session, before the first message. Most
 * sessions need the *index* of the language — which terms exist and what each
 * is in one sentence — and only a naming or issue-writing task needs the full
 * entry with its `_Avoid_` list and decision history. The brief is that index.
 *
 * Generated, never hand-edited: the glossary stays the source of truth and the
 * brief is rebuilt from it, so the two cannot disagree. Run after editing
 * `CONTEXT.md` or the orientation table in `OVERVIEW.md`:
 *
 *     node scripts/context-brief.mjs [repo-root]
 *
 * Both inputs are gitignored and live only in the canonical checkout. The root
 * defaults to the current directory; from a worktree, pass the canonical
 * checkout explicitly.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The first sentence of a definition, capped so a long entry stays one line. */
export function firstSentence(text, cap = 220) {
  const clean = text.replace(/\s+/g, ' ').trim();
  const m = clean.match(/^.*?[.!?](?=\s|$)/);
  const sentence = (m ? m[0] : clean).trim();
  return sentence.length > cap ? `${sentence.slice(0, cap - 1).trimEnd()}…` : sentence;
}

/**
 * A bold lead-in that is a *term*: a noun phrase, not a sentence. The glossary
 * also opens paragraphs in bold — "Deliberately not a property of the race." —
 * and those are prose, not vocabulary to "use exactly". A term has no terminal
 * punctuation and is short.
 */
export function isTermName(name) {
  const trimmed = name.trim();
  return !/[.:!?]$/.test(trimmed) && trimmed.split(/\s+/).length <= 8;
}

/**
 * `## Section` headings and `**Term** — definition` lines out of the glossary,
 * in order. A term line may be a top-level `**Term**` or a nested `- **Term**`;
 * the definition is whatever follows the closing `**` and a dash.
 */
export function glossaryIndex(markdown) {
  const out = [];
  // Split on either line ending: `.` does not match `\r`, so a CRLF file would
  // otherwise fail every `(.*)$` below and the index would come out empty.
  for (const line of markdown.split(/\r?\n/)) {
    const h = line.match(/^## (.+)$/);
    if (h) {
      out.push({ section: h[1].trim() });
      continue;
    }
    const t = line.match(/^(?:- )?\*\*([^*]+)\*\*\s*[—–-]?\s*(.*)$/);
    // A bold line with nothing after it is a heading in bold; a bold sentence is
    // prose. Neither is a term.
    if (t && t[2].trim() && isTermName(t[1])) out.push({ term: t[1].trim(), definition: firstSentence(t[2]) });
  }
  return out;
}

/** The `## Orientation — where truth lives` section of OVERVIEW.md, verbatim. */
export function orientation(markdown) {
  const start = markdown.indexOf('## Orientation');
  if (start === -1) return '';
  const rest = markdown.slice(start);
  const next = rest.indexOf('\n## ', 1);
  return (next === -1 ? rest : rest.slice(0, next)).trim();
}

export function renderBrief(context, overview) {
  const lines = [
    '# Context brief',
    '',
    '_Generated by `scripts/context-brief.mjs` from `OVERVIEW.md` and `CONTEXT.md`. Do not edit;',
    'rebuild after changing either. This is the **index** of the domain language — one sentence per',
    'term. The full entry, its `_Avoid_` list and the decisions behind it are in `CONTEXT.md`: read',
    'that file before naming anything new, writing an issue, PRD or ADR, or when a term here is not',
    'enough. `OVERVIEW.md` §"Current state" is the long-form status; the route itself is the MAP below._',
    '',
    orientation(overview),
    '',
    '## Glossary index',
    '',
    'Use these terms exactly; do not drift to synonyms.',
    '',
  ];
  for (const entry of glossaryIndex(context)) {
    if (entry.section) lines.push('', `### ${entry.section}`, '');
    else lines.push(`- **${entry.term}** — ${entry.definition}`);
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
}

function main(argv) {
  const root = resolve(argv[2] ?? process.cwd());
  const contextPath = join(root, 'CONTEXT.md');
  const overviewPath = join(root, 'OVERVIEW.md');
  for (const p of [contextPath, overviewPath]) {
    if (!existsSync(p)) {
      console.error(`context-brief: ${p} not found — pass the canonical checkout as the argument.`);
      process.exit(1);
    }
  }
  const brief = renderBrief(readFileSync(contextPath, 'utf8'), readFileSync(overviewPath, 'utf8'));
  const outPath = join(root, 'CONTEXT-BRIEF.md');
  writeFileSync(outPath, brief, 'utf8');
  const terms = (brief.match(/^- \*\*/gm) ?? []).length;
  console.log(`context-brief: wrote ${outPath} — ${terms} terms, ${brief.length} chars (~${Math.round(brief.length / 4)} tokens)`);
}

// Only when run as a script: the pure functions above are importable by tests.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main(process.argv);
