/**
 * Narration: turning a Head Coach's action into something the Coach says.
 *
 * ADR-0003 calls "no silent plan mutations" a non-negotiable trust rule. The
 * audit half has always shipped — every Head Coach action writes an attributed
 * `events` row — but the athlete-facing half was benched for the
 * single-real-athlete eval. This module is that half: pure, so what the Coach
 * says about a plan change is decided by data rather than by a model.
 *
 * **Deliberately not generated by the LLM** (ticket `coached-mode/03`, plan
 * decision 2). The event payload already holds everything the sentence needs,
 * so a model could only add invention about a change the athlete did not make;
 * an API call would put cost, latency and a failure mode on every View render;
 * and text this module composes can be tested, which is what makes narration
 * something a build can prove rather than something a human has to go and read.
 */

/** The Coach's own two announcements (`training-architecture/07`). */
export type CoachNarratableType = 'blocks_drafted' | 'race_flagged_unrealistic' | 'week_drafted';

/** The Head Coach's session actions — the events {@link clause} renders. */
export type HeadCoachNarratableType =
  | 'session_prescribed'
  | 'session_edited'
  | 'session_deleted'
  | 'session_moved';

/**
 * A Head Coach's hand on the Training Blocks: an edit (`training-architecture/08`,
 * rendered by {@link blockClause}) or a re-pin of a set the race moved out
 * from under (`/19`, rendered by {@link blocksRepinnedClause}).
 */
export type BlockNarratableType = 'block_edited' | 'blocks_repinned';

/** A Head Coach's hand on the drafted week or its day (`training-architecture/17`). */
export type WeekNarratableType = 'weekly_session_day_set' | 'week_draft_approved';

/** A plan change by another hand worth telling the athlete about. */
export interface NarratableEvent {
  id: string;
  /**
   * The acting Head Coach's opaque coach id. Null for the Coach's own events,
   * which have no actor to name — and null for malformed Head Coach history.
   */
  actorId: string | null;
  type: HeadCoachNarratableType | BlockNarratableType | WeekNarratableType | CoachNarratableType;
  /** `jsonb`, so genuinely unknown until narrowed. */
  payload: unknown;
  createdAt: Date;
}

/** Renders one message key with its values — next-intl's `t`, narrowed. */
export type Translate = (
  key: string,
  values?: Record<string, string | number>,
) => string;

/** Turns a `YYYY-MM-DD` into a weekday in the athlete's language. */
export type WeekdayOf = (dateKey: string) => string;

/**
 * Reads one string field out of a `jsonb` payload, or undefined.
 *
 * Defensive on purpose: `payload` is whatever was written when the event
 * happened, and this runs on app-open. A malformed payload must degrade to a
 * plainer sentence, never throw — a throw here would break every View for that
 * athlete, which is a far worse failure than a vague one.
 */
function field(payload: unknown, ...path: string[]): string | undefined {
  let node: unknown = payload;
  for (const key of path) {
    if (node === null || typeof node !== 'object') return undefined;
    node = (node as Record<string, unknown>)[key];
  }
  // An empty or whitespace-only string is absent: every caller treats a falsy
  // field as missing, so `||` is the whole rule rather than a separate check.
  return typeof node === 'string' ? node.trim() || undefined : undefined;
}

/**
 * The day and session type a narration clause needs, per event kind.
 *
 * The payloads are not the same shape, and the difference is not cosmetic: an
 * edit records `to` (the new content) beside `from` (where it was), and **a
 * delete records no session type at all** — `head-coach-service` writes
 * `{ sessionId, date, origin }`. So a deleted session is narrated without
 * naming its kind, because the event does not know it. Inventing one would be
 * exactly the fabrication this module exists to avoid.
 *
 * A move is the odd one. `session-move` writes `{ sessionId, from, to }` with
 * both days as bare date strings rather than nested objects — so `from` here is
 * a *day*, where an edit's `from` is a whole session. And like a delete it
 * carries no type, so a move is narrated without naming the session's kind.
 * What a move needs instead is the second day: "moved" is the one action whose
 * meaning is the pair, not the destination.
 */
function subject(event: NarratableEvent & { type: HeadCoachNarratableType }): {
  day?: string;
  type?: string;
  fromDay?: string;
} {
  switch (event.type) {
    case 'session_prescribed':
      return { day: field(event.payload, 'date'), type: field(event.payload, 'type') };
    case 'session_edited':
      return {
        day: field(event.payload, 'to', 'date') ?? field(event.payload, 'from', 'date'),
        type: field(event.payload, 'to', 'type'),
      };
    case 'session_deleted':
      return { day: field(event.payload, 'date') };
    case 'session_moved':
      return {
        day: field(event.payload, 'to'),
        fromDay: field(event.payload, 'from'),
      };
  }
}

/**
 * The block names out of a `blocks_drafted` payload, or undefined when the list
 * is not there or holds anything that is not a named block. Half a list would
 * announce half the plan, so it is all or the no-detail sentence.
 */
function blockNames(payload: unknown): string[] | undefined {
  const blocks = (payload as { blocks?: unknown } | null)?.blocks;
  if (!Array.isArray(blocks) || blocks.length === 0) return undefined;
  const names = blocks.map((b) => field(b, 'name'));
  return names.every((n): n is string => n !== undefined) ? names : undefined;
}

/** Whether an event is the Coach's own, rendered by {@link coachClause}. */
function isCoachEvent(
  event: NarratableEvent,
): event is NarratableEvent & { type: CoachNarratableType } {
  return (
    event.type === 'blocks_drafted' ||
    event.type === 'race_flagged_unrealistic' ||
    event.type === 'week_drafted'
  );
}

/**
 * The Coach speaking about its own change — so there is no `{coach}` in these
 * keys, and no fallback to "your Head Coach". The distinction is the point of
 * the acceptance criterion: an automatic adjustment is announced as the Coach's,
 * naming no human. A `coach_ai` event pushed through {@link clause} would have
 * been attributed to a person who did nothing.
 */
function coachClause(event: NarratableEvent, t: Translate, weekdayOf: WeekdayOf): string {
  switch (event.type) {
    case 'week_drafted':
      return weekDraftedClause(event.payload, t, weekdayOf);
    case 'race_flagged_unrealistic':
      return unrealisticClause(event.payload, t);
    default:
      return blocksDraftedClause(event.payload, t);
  }
}

/**
 * A drafted week (`training-architecture/16`): one sentence, no session list —
 * the proposal itself is on the calendar. It names the day training starts,
 * the earliest session's, because the draft may be this week's remainder or
 * next week (`/24`) and "next week" would be wrong half the time; with no
 * dated session, or a malformed payload, the sentence has no day.
 */
function weekDraftedClause(payload: unknown, t: Translate, weekdayOf: WeekdayOf): string {
  const first = firstSessionDate(payload);
  return first ? t('weekDraftedFrom', { day: weekdayOf(first) }) : t('weekDrafted');
}

/** The earliest `date` among the payload's sessions, or undefined when none is dated. */
function firstSessionDate(payload: unknown): string | undefined {
  const sessions = (payload as { sessions?: unknown } | null)?.sessions;
  if (!Array.isArray(sessions)) return undefined;
  // ISO date keys sort as dates and `sort` puts undefined last, so the first
  // is the earliest dated session — or undefined when none is dated.
  return sessions.map((s) => field(s, 'date')).sort()[0];
}

/** No weekday here, unlike every session clause: a race is months out and its weekday says nothing. */
function unrealisticClause(payload: unknown, t: Translate): string {
  return t('raceUnrealistic', {
    race: field(payload, 'raceName') ?? t('yourRace'),
    reason: field(payload, 'reason') ?? t('noReason'),
  });
}

/**
 * The Coach's own shaping — or, in the solo case (`training-architecture/19`,
 * ruling 2), its re-fit of a former Head Coach's blocks after the race moved
 * and nobody was left linked to re-pin them. The second is a different
 * sentence because it says whose blocks went: a fresh draft announced over a
 * human's structure as if it had never been there would be the silent
 * overwrite ADR 0003 forbids, one step removed.
 */
function blocksDraftedClause(payload: unknown, t: Translate): string {
  const refitted = (payload as { refittedHeadCoachBlocks?: unknown } | null)?.refittedHeadCoachBlocks === true;
  const race = field(payload, 'raceName');
  const names = blockNames(payload);
  if (!race || !names) return t(refitted ? 'blocksRefittedNoDetail' : 'blocksDraftedNoDetail');
  return t(refitted ? 'blocksRefitted' : 'blocksDrafted', { race, blocks: names.join(' · ') });
}

/**
 * The Head Coach re-pinned a set to the race's new date (`training-architecture/19`),
 * by one click or by starting over from the draft: one sentence either way,
 * because what the athlete needs to know is the same — their blocks fit the
 * race again, and whose hand did it.
 */
function blocksRepinnedClause(event: NarratableEvent, coachFirstNames: Record<string, string>, t: Translate): string {
  const coach = (event.actorId ? coachFirstNames[event.actorId] : undefined) ?? t('yourHeadCoach');
  const race = field(event.payload, 'raceName');
  return race ? t('blocksRepinned', { coach, race }) : t('blocksRepinnedNoDetail', { coach });
}

const CLAUSE_KEY = {
  session_prescribed: 'prescribed',
  session_edited: 'edited',
  session_deleted: 'deleted',
  session_moved: 'moved',
} as const;

/**
 * Which message key a Head Coach event renders with.
 *
 * A delete never carries a type, and any payload can be malformed — so there
 * is a typeless phrasing for every kind rather than a placeholder word.
 *
 * A move varies on the other axis. It never carries a type either, so the
 * `NoType` suffix would be its only spelling and says nothing; what it can
 * lose is the day it came *from*, and a move missing that is a different
 * sentence rather than a vaguer one.
 */
function clauseKey(type: HeadCoachNarratableType, sessionType?: string, fromDay?: string): string {
  if (type === 'session_moved') return fromDay ? 'moved' : 'movedNoFrom';
  return `${CLAUSE_KEY[type]}${sessionType ? '' : 'NoType'}`;
}

/** One event as one sentence, attributed to the coach who actually acted. */
function clause(
  event: NarratableEvent & { type: HeadCoachNarratableType },
  coachFirstNames: Record<string, string>,
  t: Translate,
  weekdayOf: WeekdayOf,
): string {
  const { day, type, fromDay } = subject(event);
  // The name comes from the event's own `actorId`, never from the athlete's
  // *current* link: an athlete who severed and re-linked must not see the new
  // coach's name on the old coach's change.
  const coach =
    (event.actorId ? coachFirstNames[event.actorId] : undefined) ??
    t('yourHeadCoach');
  const values = {
    coach,
    day: day ? weekdayOf(day) : t('recently'),
    ...(type ? { type } : {}),
    ...(fromDay ? { fromDay: weekdayOf(fromDay) } : {}),
  };
  const key = clauseKey(event.type, type, fromDay);
  // **The Head Coach's note is deliberately not read** (Mads, 2026-08-21). It
  // is the one honest source of a *reason* — "he wants you race-sharp" — and
  // dropping it costs real warmth. But it is human free text, and this sentence
  // is stored in the Coach Chat transcript, which `toApiMessages` replays to
  // Anthropic on every later turn: a coach writing "I want you sharp for Lars's
  // ride" would put a name in front of the model for the rest of that athlete's
  // history. `assertNoDirectIdentifier` cannot catch that — it recognises email
  // and phone *shapes*, never a name in prose — so the guarantee has to be
  // structural: the note is not sent, rather than filtered.
  //
  // Restoring it for the athlete alone would need the transcript to separate
  // what is displayed from what is replayed to the model, which it does not.
  return t(key, values);
}

/**
 * A Head Coach's block edit as one sentence (`training-architecture/08`).
 *
 * Attributed like every other human clause — the acting coach's name, or "your
 * Head Coach". The end date is rendered as the date key itself, not a weekday:
 * a block ends months out, and its weekday says nothing. What changed decides
 * the sentence: the name, the end, or both; a payload missing either side
 * degrades to the plain "changed a block" rather than inventing a before.
 */
type BlockSide = { name: string; day: string };

/** One side of a block edit, or undefined when the payload does not carry both halves. */
function blockSide(payload: unknown, side: 'from' | 'to'): BlockSide | undefined {
  const name = field(payload, side, 'name');
  const day = field(payload, side, 'endDate');
  return name && day ? { name, day } : undefined;
}

/** Which sentence a block edit is, from what actually changed — the key and exactly its values. */
function blockEditSentence(
  from: BlockSide,
  to: BlockSide,
): { key: string; values: Record<string, string> } {
  const renamed = from.name !== to.name;
  const rebounded = from.day !== to.day;
  if (renamed && rebounded) {
    return { key: 'blockRenamedAndRebounded', values: { from: from.name, to: to.name, day: to.day } };
  }
  if (renamed) return { key: 'blockRenamed', values: { from: from.name, to: to.name } };
  return rebounded
    ? { key: 'blockRebounded', values: { name: to.name, day: to.day } }
    : { key: 'blockEditedNoDetail', values: {} };
}

function blockClause(
  event: NarratableEvent,
  coachFirstNames: Record<string, string>,
  t: Translate,
): string {
  const coach = (event.actorId ? coachFirstNames[event.actorId] : undefined) ?? t('yourHeadCoach');
  const from = blockSide(event.payload, 'from');
  const to = blockSide(event.payload, 'to');
  if (!from || !to) return t('blockEditedNoDetail', { coach });
  const sentence = blockEditSentence(from, to);
  return t(sentence.key, { coach, ...sentence.values });
}

/**
 * The Head Coach moved the athlete's Weekly Session Day, or shaped the drafted
 * week before it reached them (`training-architecture/17`). Attributed like
 * every other human clause. The day is rendered through the catalogue's own
 * weekday keys, never the stored English name.
 */
function weekClause(event: NarratableEvent, coachFirstNames: Record<string, string>, t: Translate): string {
  const coach = (event.actorId ? coachFirstNames[event.actorId] : undefined) ?? t('yourHeadCoach');
  if (event.type === 'week_draft_approved') return t('weekDraftShaped', { coach });
  const to = field(event.payload, 'to');
  return to ? t('weeklyDaySet', { coach, day: t(`day${to}`) }) : t('weeklyDaySetNoDetail', { coach });
}

/**
 * Everything the Head Coach has done since the athlete was last told, as **one**
 * message.
 *
 * One message, not one per event, because these arrive as a batch the first
 * time the athlete opens the app after a coaching session — and N separate
 * Coach turns for one afternoon's planning reads as a malfunction, not as
 * coaching. Returns null when there is nothing to say, so the caller has a
 * single thing to check before it writes anything.
 */
export function composeNarration(
  events: NarratableEvent[],
  coachFirstNames: Record<string, string>,
  t: Translate,
  weekdayOf: WeekdayOf,
): string | null {
  if (events.length === 0) return null;

  // Clauses are composed unpunctuated so the catalogue decides how a sentence
  // and a list item are each finished — punctuation differs by language, and it
  // is copy, not logic.
  const clauses = events.map((e) => {
    if (isCoachEvent(e)) return coachClause(e, t, weekdayOf);
    if (e.type === 'weekly_session_day_set' || e.type === 'week_draft_approved') {
      return weekClause(e, coachFirstNames, t);
    }
    if (e.type === 'block_edited') return blockClause(e, coachFirstNames, t);
    if (e.type === 'blocks_repinned') return blocksRepinnedClause(e, coachFirstNames, t);
    return clause(e as NarratableEvent & { type: HeadCoachNarratableType }, coachFirstNames, t, weekdayOf);
  });
  if (clauses.length === 1) return t('single', { clause: clauses[0] });

  return [
    t('multiLead'),
    ...clauses.map((c) => t('item', { clause: c })),
  ].join('\n');
}
