/**
 * Narration: turning a Head Coach's action into something the Coach says.
 *
 * ADR-0003 calls "no silent plan mutations" a non-negotiable trust rule. The
 * audit half has always shipped — every Head Coach action writes an attributed
 * `events` row — but the athlete-facing half was benched for the
 * single-real-athlete eval. This module is that half: pure, so what the Coach
 * says about a plan change is decided by data rather than by a model.
 *
 * **Deliberately not generated by the LLM** (ticket `coached-mode/03`, plan
 * decision 2). The event payload already holds everything the sentence needs,
 * so a model could only add invention about a change the athlete did not make;
 * an API call would put cost, latency and a failure mode on every View render;
 * and text this module composes can be tested, which is what makes narration
 * something a build can prove rather than something a human has to go and read.
 */

/** A Head Coach action worth telling the athlete about. */
export interface NarratableEvent {
  id: string;
  /** The acting Head Coach's opaque coach id — null only for malformed history. */
  actorId: string | null;
  type:
    | 'session_prescribed'
    | 'session_edited'
    | 'session_deleted'
    | 'session_moved';
  /** `jsonb`, so genuinely unknown until narrowed. */
  payload: unknown;
  createdAt: Date;
}

/** Renders one message key with its values — next-intl's `t`, narrowed. */
export type Translate = (
  key: string,
  values?: Record<string, string | number>,
) => string;

/** Turns a `YYYY-MM-DD` into a weekday in the athlete's language. */
export type WeekdayOf = (dateKey: string) => string;

/**
 * Reads one string field out of a `jsonb` payload, or undefined.
 *
 * Defensive on purpose: `payload` is whatever was written when the event
 * happened, and this runs on app-open. A malformed payload must degrade to a
 * plainer sentence, never throw — a throw here would break every View for that
 * athlete, which is a far worse failure than a vague one.
 */
function field(payload: unknown, ...path: string[]): string | undefined {
  let node: unknown = payload;
  for (const key of path) {
    if (node === null || typeof node !== 'object') return undefined;
    node = (node as Record<string, unknown>)[key];
  }
  return typeof node === 'string' && node.trim() !== '' ? node.trim() : undefined;
}

/**
 * The day and session type a narration clause needs, per event kind.
 *
 * The payloads are not the same shape, and the difference is not cosmetic: an
 * edit records `to` (the new content) beside `from` (where it was), and **a
 * delete records no session type at all** — `head-coach-service` writes
 * `{ sessionId, date, origin }`. So a deleted session is narrated without
 * naming its kind, because the event does not know it. Inventing one would be
 * exactly the fabrication this module exists to avoid.
 *
 * A move is the odd one. `session-move` writes `{ sessionId, from, to }` with
 * both days as bare date strings rather than nested objects — so `from` here is
 * a *day*, where an edit's `from` is a whole session. And like a delete it
 * carries no type, so a move is narrated without naming the session's kind.
 * What a move needs instead is the second day: "moved" is the one action whose
 * meaning is the pair, not the destination.
 */
function subject(event: NarratableEvent): {
  day?: string;
  type?: string;
  fromDay?: string;
} {
  switch (event.type) {
    case 'session_prescribed':
      return { day: field(event.payload, 'date'), type: field(event.payload, 'type') };
    case 'session_edited':
      return {
        day: field(event.payload, 'to', 'date') ?? field(event.payload, 'from', 'date'),
        type: field(event.payload, 'to', 'type'),
      };
    case 'session_deleted':
      return { day: field(event.payload, 'date') };
    case 'session_moved':
      return {
        day: field(event.payload, 'to'),
        fromDay: field(event.payload, 'from'),
      };
  }
}

const CLAUSE_KEY = {
  session_prescribed: 'prescribed',
  session_edited: 'edited',
  session_deleted: 'deleted',
  session_moved: 'moved',
} as const;

/** One event as one sentence, attributed to the coach who actually acted. */
function clause(
  event: NarratableEvent,
  coachFirstNames: Record<string, string>,
  t: Translate,
  weekdayOf: WeekdayOf,
): string {
  const { day, type, fromDay } = subject(event);
  // The name comes from the event's own `actorId`, never from the athlete's
  // *current* link: an athlete who severed and re-linked must not see the new
  // coach's name on the old coach's change.
  const coach =
    (event.actorId ? coachFirstNames[event.actorId] : undefined) ??
    t('yourHeadCoach');
  const values = {
    coach,
    day: day ? weekdayOf(day) : t('recently'),
    ...(type ? { type } : {}),
    ...(fromDay ? { fromDay: weekdayOf(fromDay) } : {}),
  };
  // A delete never carries a type, and any payload can be malformed — so there
  // is a typeless phrasing for every kind rather than a placeholder word.
  //
  // A move varies on the other axis. It never carries a type either, so the
  // `NoType` suffix would be its only spelling and says nothing; what it can
  // lose is the day it came *from*, and a move missing that is a different
  // sentence rather than a vaguer one.
  const key =
    event.type === 'session_moved'
      ? fromDay
        ? 'moved'
        : 'movedNoFrom'
      : `${CLAUSE_KEY[event.type]}${type ? '' : 'NoType'}`;
  // **The Head Coach's note is deliberately not read** (Mads, 2026-08-21). It
  // is the one honest source of a *reason* — "he wants you race-sharp" — and
  // dropping it costs real warmth. But it is human free text, and this sentence
  // is stored in the Coach Chat transcript, which `toApiMessages` replays to
  // Anthropic on every later turn: a coach writing "I want you sharp for Lars's
  // ride" would put a name in front of the model for the rest of that athlete's
  // history. `assertNoDirectIdentifier` cannot catch that — it recognises email
  // and phone *shapes*, never a name in prose — so the guarantee has to be
  // structural: the note is not sent, rather than filtered.
  //
  // Restoring it for the athlete alone would need the transcript to separate
  // what is displayed from what is replayed to the model, which it does not.
  return t(key, values);
}

/**
 * Everything the Head Coach has done since the athlete was last told, as **one**
 * message.
 *
 * One message, not one per event, because these arrive as a batch the first
 * time the athlete opens the app after a coaching session — and N separate
 * Coach turns for one afternoon's planning reads as a malfunction, not as
 * coaching. Returns null when there is nothing to say, so the caller has a
 * single thing to check before it writes anything.
 */
export function composeNarration(
  events: NarratableEvent[],
  coachFirstNames: Record<string, string>,
  t: Translate,
  weekdayOf: WeekdayOf,
): string | null {
  if (events.length === 0) return null;

  // Clauses are composed unpunctuated so the catalogue decides how a sentence
  // and a list item are each finished — punctuation differs by language, and it
  // is copy, not logic.
  const clauses = events.map((e) => clause(e, coachFirstNames, t, weekdayOf));
  if (clauses.length === 1) return t('single', { clause: clauses[0] });

  return [
    t('multiLead'),
    ...clauses.map((c) => t('item', { clause: c })),
  ].join('\n');
}
